### ISSUE TITLE
reloaded.repl / system.repl inconsistency

### ISSUE THREAD

**Issue by martinklepsch** [danielsz/system#97] opened 2016-09-20 15:45 UTC
`reloaded.repl/set-init!` expects a function whereas `system.repl/set-init!` needs a var. Given that people may be used to `reloaded.repl` an extra
```clojure
{:pre [(var? sys)]}
```
might be warranted.

**Comment by danielsz** [comment] 2016-09-20 16:22
Thank you, @martinklepsch . This check is already in place. :-)

https://github.com/danielsz/system/blob/master/src/system/boot.clj#L28

**Comment by martinklepsch** [comment] 2016-09-20 16:29
I'm actually thinking of a check in `set-init!`, not in the `system` task.

**Comment by danielsz** [comment] 2016-09-20 16:39
I'm not sure why you are bothered that system does its validation in a different place.

**Comment by martinklepsch** [comment] 2016-09-20 16:47
It's not that I'm bothered it's doing it in a different place it's more that `reloaded.repl` has been replaced by `system.repl` and if users are expecting these namespaces to be mostly identic they'll pass a function to `set-init!` vs. a var as expected by `system.repl`. This has nothing to do with the boot task or similar, it's purely an idea/suggestion to make `system.repl` more user-friendly (especially for people familiar with `reloaded.repl`)

.If I wouldn't have ran into #96 I'd never have run into this either but the error message when calling `set-init!` on a function is horrible and I think deserves to be improved no matter if people are expected to be using it in the usual case.

Hope that makes sense :)

**Comment by martinklepsch** [comment] 2016-09-20 16:58
![screenshot 2016-09-20 18 50 21](https://cloud.githubusercontent.com/assets/97496/18680236/1d7a228a-7f63-11e6-8a2f-5e5936448495.png)

This is the error when you call `set-init` the way you'd usually call `reloaded.repl/set-init!`.

**Comment by danielsz** [comment] 2016-09-20 17:01
I see.

`set-init!` is a private call. It is used internally by the boot task. 
If a user misconfigures the system in the boot task, he will get a friendly error message.
You ran into #96 because of a regression. With the fix, the boot task will always set the system with `set-init`. If `auto` is specified, system handles reloading and restarts. If not, the user can refresh manually (but the system will be initialized and started).

Does this make sense?.

**Comment by martinklepsch** [comment] 2016-09-20 17:06
I guess I'm pushing a bit too much on the point that `system.repl` is the system-specific pendant to `reloaded.repl`. In `reloaded.repl` `set-init!` is considered part of the API and I'd think if you provide a replacement namespace it exposes a similar API.

Even if this codepath is unlikely to be taken directly I feel like the change would be a small one, in the favour of the user. 👍

I guess there's not much more I could say about it at this point.

**Comment by danielsz** [comment] 2016-09-21 11:50
When you discovered that `set-init!` wasn't called when `auto` was set to false, you did the right thing, you opened an issue. (It is fixed now). When you called `set-init!` yourself to get work done, you did what any hacker would do, and that's great. 

It so happens that `boot.system` uses `reloaded.repl` internally. Users may or may not know that fact. These are implementation details, after all. If you hack your way in and are surprised that they actually diverged somewhat, it is understandable, but wishing they wouldn't have seems unwarranted. No claims are being made regarding their correspondence. `system` takes some liberties with `tools.namespace` as well. And for the same good reason that `system` is driven by its own concerns.
 
If you got an error because you passed a function instead of a Var, that is bad only in the sense that you had to resort to calling `set-init!` yourself in the first place. 

The way a user sets a system is via the `sys` keyword. If `auto` is true, system restarts will be managed automatically, otherwise `sys` is initialized and the user handles restarts manually at the REPL.

Type `boot system -h` at the CLI or the equivalent  at the REPL, and there you have our API. Nothing more, nothing less. Making sure that the options are properly explained and that everything works as advertised, that is in my opinion serving the user's best interest. 

Thank you for arguing and pushing and whatnot. :+1:  This gives me an opportunity to clarify my positions and polishing the product, so to speak.

**Comment by danielsz** [comment] 2016-09-27 03:02
Feel free to reopen if there's something else.

**Closed by danielsz** 2016-09-27 03:02 UTC
