### ISSUE TITLE
Calling `set-init!` when not using `:auto`

### ISSUE THREAD

**Issue by martinklepsch** [danielsz/system#96] opened 2016-09-16 18:16 UTC
I got caught by surprise that `set-init!` isn't called when not using the `:auto` option. Is there any specific reasoning behind this? Maybe we could move the `set-init` call outside of the `(when auto ...)` check?

https://github.com/danielsz/system/blob/master/src/system/boot.clj#L55-L71

**Comment by danielsz** [comment] 2016-09-20 12:56
Yes, you are right. This is actually a regression, because that's how it's supposed to work. If `auto` is false, user should be able to start and stop manually at the REPL.
Will take care of it. Thanks!

**Comment by danielsz** [comment] 2016-09-21 11:54
Fixed in `0.3.2-SNAPSHOT`

**Closed** 2016-09-21 11:54 UTC
